"""story metadata fields

Revision ID: 4c1e7f77790b
Revises: 9dec6275973e
Create Date: 2026-06-05 00:07:05.059632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c1e7f77790b'
down_revision: Union[str, None] = '9dec6275973e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('genres', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('stories', sa.Column('moods', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('stories', sa.Column('content_rating', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.drop_column('stories', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('stories', 'content_rating')
    op.drop_column('stories', 'moods')
    op.drop_column('stories', 'genres')
    # ### end Alembic commands ###
